FROM golang:1.24 AS build

COPY . /app
WORKDIR /app

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o /cqrs-es-example-go

FROM public.ecr.aws/lambda/provided:al2
COPY --from=build /cqrs-es-example-go /var/runtime/bootstrap
CMD [ "lambda-handler" ]
