// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package query

// グループチャットリードモデル
//
// NOTE: リードモデルはDTOとして利用されるものです。
// 特段振る舞いのようなものはありません。
type GroupChat struct {
	// グループチャットID
	ID string `json:"id"`
	// グループチャット名
	Name string `json:"name"`
	// 管理者ID
	OwnerID string `json:"ownerId"`
	// 作成日時
	CreatedAt string `json:"createdAt"`
	// 更新日時
	UpdatedAt string `json:"updatedAt"`
}

// メンバーリードモデル
type Member struct {
	// メンバーID
	ID string `json:"id"`
	// グループチャットID
	GroupChatID string `json:"groupChatId"`
	// アカウントID
	UserAccountID string `json:"userAccountId"`
	// ロール
	Role string `json:"role"`
	// 作成日時
	CreatedAt string `json:"createdAt"`
	// 更新日時
	UpdatedAt string `json:"updatedAt"`
}

// メッセージリードモデル
type Message struct {
	// メッセージID
	ID string `json:"id"`
	// グループチャットID
	GroupChatID string `json:"groupChatId"`
	// アカウントID
	UserAccountID string `json:"userAccountId"`
	// メッセージ本文
	Text string `json:"text"`
	// 作成日時
	CreatedAt string `json:"createdAt"`
	// 更新日時
	UpdatedAt string `json:"updatedAt"`
}

type QueryRoot struct {
}

// https://github.com/async-graphql/examples/blob/c8219078a4b7aa6d84d22e9b79f033088897be4b/poem/subscription-redis/src/main.rs
type SubscriptionRoot struct {
}
