package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	query "cqrs-es-example-go/pkg/query/graph/model"
	"fmt"
	"time"
)

// GetGroupChat is the resolver for the getGroupChat field.
func (r *queryRootResolver) GetGroupChat(ctx context.Context, groupChatID string, userAccountID string) (*query.GroupChat, error) {
	stmt, err := r.db.Prepare(`SELECT gc.id, gc.name, gc.owner_id, gc.created_at FROM group_chats AS gc JOIN members AS m ON gc.id = m.group_chat_id WHERE m.group_chat_id = ? AND m.account_id = ?`)
	defer stmt.Close()
	if err != nil {
		return nil, err
	}
	row := stmt.QueryRow(groupChatID, userAccountID)
	if row != nil {
		var id string
		var name string
		var ownerID string
		var createdAt time.Time
		err = row.Scan(&id, &name, &ownerID, &createdAt)
		if err != nil {
			return nil, err
		}
		return &query.GroupChat{
			ID:        id,
			Name:      name,
			OwnerID:   ownerID,
			CreatedAt: createdAt.String(),
		}, nil
	}
	return nil, nil
}

// GetGroupChats is the resolver for the getGroupChats field.
func (r *queryRootResolver) GetGroupChats(ctx context.Context, userAccountID string) ([]*query.GroupChat, error) {
	panic(fmt.Errorf("not implemented: GetGroupChats - getGroupChats"))
}

// GetMember is the resolver for the getMember field.
func (r *queryRootResolver) GetMember(ctx context.Context, groupChatID string, userAccountID string) (*query.Member, error) {
	panic(fmt.Errorf("not implemented: GetMember - getMember"))
}

// GetMembers is the resolver for the getMembers field.
func (r *queryRootResolver) GetMembers(ctx context.Context, groupChatID string, userAccountID string) ([]*query.Member, error) {
	panic(fmt.Errorf("not implemented: GetMembers - getMembers"))
}

// GetMessage is the resolver for the getMessage field.
func (r *queryRootResolver) GetMessage(ctx context.Context, messageID string, userAccountID string) (*query.Message, error) {
	stmt, err := r.db.Prepare(`SELECT m.id, m.group_chat_id, m.account_id, m.text, m.created_at FROM ( SELECT * FROM messages WHERE id = ? ) AS m WHERE EXISTS( SELECT 1 FROM members AS mem WHERE mem.group_chat_id = m.group_chat_id AND mem.account_id = ? )`)
	defer stmt.Close()
	if err != nil {
		return nil, err
	}
	row := stmt.QueryRow(messageID, userAccountID)
	if row != nil {
		var id string
		var groupChatId string
		var userAccountId string
		var text string
		var createdAt time.Time
		err = row.Scan(&id, &groupChatId, &userAccountId, &text, &createdAt)
		if err != nil {
			return nil, err
		}
		return &query.Message{
			ID:            id,
			GroupChatID:   groupChatId,
			UserAccountID: userAccountId,
			Text:          text,
			CreatedAt:     createdAt.String(),
		}, nil
	}
	return nil, nil
}

// GetMessages is the resolver for the getMessages field.
func (r *queryRootResolver) GetMessages(ctx context.Context, groupChatID string, userAccountID string) ([]*query.Message, error) {
	panic(fmt.Errorf("not implemented: GetMessages - getMessages"))
}

// GroupChats is the resolver for the groupChats field.
func (r *subscriptionRootResolver) GroupChats(ctx context.Context, groupChatID string) (<-chan string, error) {
	panic(fmt.Errorf("not implemented: GroupChats - groupChats"))
}

// QueryRoot returns QueryRootResolver implementation.
func (r *Resolver) QueryRoot() QueryRootResolver { return &queryRootResolver{r} }

// SubscriptionRoot returns SubscriptionRootResolver implementation.
func (r *Resolver) SubscriptionRoot() SubscriptionRootResolver { return &subscriptionRootResolver{r} }

type queryRootResolver struct{ *Resolver }
type subscriptionRootResolver struct{ *Resolver }
